#!/bin/bash
#SBATCH --job-name=covidabm
#SBATCH --time=06:00:00
#SBATCH --ntasks=1
#SBATCH --mem-per-cpu=6G
#SBATCH --cpus-per-task=1
#SBATCH --output=slurm_outputs/worsevaccines_matlab_R-%A_%a.out

module load matlab

matlab -nodisplay -r "cd '~/cm37/prod/Le/Waning_Immunity 2';disp(pwd);sev_mat=[0.6,1/5,1/15];numsims=10;TP_list = {'0.85','0.9','0.95','1.0','1.05', '1.1','1.15', '1.2','1.25', '1.3','1.35', '1.4', '1.45','1.5','1.55','1.6','1.65','1.7','1.75','1.8','1.85','1.9','1.95','2.0','2.05'};TP = TP_list{${TPvers}};disp(TP);population = '${POP}';disp(population);params = '${diffparams}';disp(params);foldername = '/scratch/cm37/tpl/covid_continuous_simulations_double_exposure_no_ttiq_450-2_outputs/';disp(foldername);filename = strcat(foldername,'abm_continuous_simulation_parameters_',population,'_',params,'_SOCRATES_TP',TP,'/');disp(filename);clinical_knitting_relsev_func(filename,sev_mat,numsims);disp('done?');quit()"


module load R/4.0.5
Rscript compress_outputs_continuous.R /scratch/cm37/tpl/covid_continuous_simulations_double_exposure_no_ttiq_450-2_outputs/ abm_continuous_simulation_parameters_${POP}_${diffparams}_SOCRATES_TP ${TPvers}