#!/bin/bash
#SBATCH --job-name=winter
#SBATCH --time=01:00:00
#SBATCH --ntasks=1
#SBATCH --mem-per-cpu=10G
#SBATCH --cpus-per-task=1
#SBATCH --array=1

module load gcc/10.2.0

for POPULATION_INPUT in younger
do
for (( PARAM_FILE=5; PARAM_FILE<=5; PARAM_FILE++ ))
do
for ((sim_i=1;sim_i<=10;sim_i++))
do
./RunWinter state_parameters/omicron_update_VE_updated.json winter_scenarios/winter_sims_${POPULATION_INPUT}_init10.json ${sim_i} initial_condition_files abm_simulation_people_params_${PARAM_FILE}_output
done
done
done
