#!/bin/bash
#SBATCH --job-name=KnitWane
#SBATCH --time=00:10:00
#SBATCH --ntasks=1
#SBATCH --mem-per-cpu=4GB
#SBATCH --cpus-per-task=1


module load matlab

matlab -nodisplay -r "sev_mat=[0.6,1/5,1/15];for ii=1:size(sev_mat,1);clinical_knitting_relsev_func('/scratch/cm37/tpl/winterwave/initial-and-during_vax_infect_scenario1_sim_params_v1_massive/',sev_mat(ii,:),3);addpath('plotting');combined_output_plotter2('/scratch/cm37/tpl/winterwave/initial-and-during_vax_infect_scenario1_sim_params_v1_massive/',sev_mat,'k');saveas(gcf,'/scratch/cm37/tpl/winterwave/initial-and-during_vax_infect_scenario1_sim_params_v1_massive_clinical_pathways.png');end;quit()"
