#!/bin/bash
#SBATCH --job-name=KnitWane
#SBATCH --time=00:45:00
#SBATCH --ntasks=1
#SBATCH --mem-per-cpu=4GB
#SBATCH --cpus-per-task=1


module load matlab

# matlab -nodisplay -r "sev_mat=[1/4,1/15,1/50];for ii=1:size(sev_mat,1);clinical_knitting_relsev_func('/scratch/cm37/health/NSW_outputs/scenario26_RestrictionScenarios_BaselineMed',sev_mat(ii,:),100);end;quit()"
matlab -nodisplay -r "sev_mat=[0.6,1/5,1/15];for ii=1:size(sev_mat,1);clinical_knitting_relsev_func('/scratch/cm37/health/NSW_outputs/scenario25_RestrictionScenarios_LowMed',sev_mat(ii,:),100);end;quit()"
# matlab -nodisplay -r "sev_mat=[1/4,1/15,1/50];for ii=1:size(sev_mat,1);clinical_knitting_relsev_func('/scratch/cm37/health/NSW_outputs/scenario26_2000Omicron_Baseline',sev_mat(ii,:),100);end;quit()"
matlab -nodisplay -r "sev_mat=[0.6,1/5,1/15];for ii=1:size(sev_mat,1);clinical_knitting_relsev_func('/scratch/cm37/health/NSW_outputs/scenario25_2000Omicron_Low',sev_mat(ii,:),100);end;quit()"

# matlab -nodisplay -r "sev_mat=[1,1,1];for ii=1:size(sev_mat,1);clinical_knitting_relsev_func('/scratch/cm37/health/NSW_outputs/scenario2_2000Omicron_Med',sev_mat(ii,:),100);end;quit()"
# matlab -nodisplay -r "sev_mat=[1,1,1];for ii=1:size(sev_mat,1);clinical_knitting_relsev_func('/scratch/cm37/health/NSW_outputs/scenario14_2000Omicron',sev_mat(ii,:),100);end;quit()"
# matlab -nodisplay -r "sev_mat=[1,1,1];for ii=1:size(sev_mat,1);clinical_knitting_relsev_func('/scratch/cm37/health/NSW_outputs/scenario14_2000Omicron_Low',sev_mat(ii,:),100);end;quit()"
# matlab -nodisplay -r "sev_mat=[1,1,1];for ii=1:size(sev_mat,1);clinical_knitting_relsev_func('/scratch/cm37/health/NSW_outputs/scenario14_2000Omicron_Med',sev_mat(ii,:),100);end;quit()"
