#!/bin/bash
#SBATCH -N 1
#SBATCH -n 1
#SBATCH -t 1:00:00
#SBATCH --mem=8GB
#SBATCH --array=1-10
#SBATCH --job-name=KnitWane

module load matlab


matlab -nodisplay -r "sev_mat=[0.6,1/5,1/15];for ii=1:size(sev_mat,1);clinical_pathways_immunity_relsev2_func('NSW','/scratch/cm37/tpl/winterwave/initial-and-during_vax_infect_scenario1_sim_params_v1_massive/sim_number_$SLURM_ARRAY_TASK_ID',sev_mat(ii,:),1);end;quit()"