#!/bin/bash
#SBATCH --job-name=covidabm
#SBATCH --time=06:00:00
#SBATCH --ntasks=1
#SBATCH --mem-per-cpu=6G
#SBATCH --cpus-per-task=1
#SBATCH --array=1-20
#SBATCH --output=BA1s_BA45s_outputs/%A_%a.out


module load gcc/10.2.0

./Run_BA1s_BA45s updated_omicron_parameters/omicron_May_2022_updates.json updated_omicron_parameters/transmission_escape_params.json json_BA1_BA45_wave_start_${BA45start}/sim_params_${POP}_${TPvers}.json $SLURM_ARRAY_TASK_ID /fs02/cm37/prod/Le/WHO/covid-abm-presim/parameter_files abm_continuous_simulation_parameters_${POP}_${diffparams}


module load matlab

matlab -nodisplay -r "cd '~/cm37/prod/Le/Waning_Immunity 2';disp(pwd);sev_mat = [1/15,1/45,1/60];TP_list = {'0.85','0.9','0.95','1.0','1.05', '1.1','1.15', '1.2','1.25', '1.3','1.35', '1.4', '1.45','1.5','1.55','1.6','1.65','1.7','1.75','1.8','1.85','1.9','1.95','2.0','2.05'};TP = TP_list{${TPvers}};disp(TP);population = '${POP}';disp(population);params = '${diffparams}';disp(params);simnum='${SLURM_ARRAY_TASK_ID}';disp(simnum);BA45wavestart = '${BA45start}';foldername = strcat('/scratch/cm37/tpl/covid_BA1_BA45_wave_start_',BA45wavestart,'_outputs/');disp(foldername);filename = strcat(foldername,'abm_continuous_simulation_parameters_',population,'_',params,'_SOCRATES_TP',TP,'/sim_number_',simnum);disp(filename);clinical_pathways_immunity_relsev3_func('NSW',filename,sev_mat);disp('done?');quit()"

