#!/bin/bash
#SBATCH --job-name=covidabm
#SBATCH --time=06:00:00
#SBATCH --ntasks=1
#SBATCH --mem-per-cpu=10G
#SBATCH --cpus-per-task=1
#SBATCH --array=1-20
#SBATCH --output=annual_boosting_1_outputs/%A_%a.out


module load gcc/10.2.0

./Run_BA1s_BA45s_cont_intros updated_omicron_parameters/omicron_May_2022_updates.json updated_omicron_parameters/transmission_escape_params.json annual_boosting_1_immune_escape_t${BA45start}/sim_params_${POP}_${TPvers}.json $SLURM_ARRAY_TASK_ID /path/to/covid-abm-presim/parameter_files_annual_boosting_1 abm_continuous_simulation_parameters_${POP}_${diffparams}

module load matlab

matlab -nodisplay -r "cd 'path/to/clinical_pathways';disp(pwd);sev_mat = [1/15,1/45,1/60];TP_list = {'1.05','1.95'};TP = TP_list{${TPvers}};disp(TP);population = '${POP}';disp(population);params = '${diffparams}';disp(params);simnum='${SLURM_ARRAY_TASK_ID}';disp(simnum);BA45wavestart = '${BA45start}';foldername = strcat('/path/to/annual_boosting_1_immune_escape_t',BA45wavestart,'_outputs/');disp(foldername);filename = strcat(foldername,'abm_continuous_simulation_parameters_',population,'_',params,'_SOCRATES_TP',TP,'/sim_number_',simnum);disp(filename);clinical_pathways_immunity_relsev3_func('NSW',filename,sev_mat);disp('done?');quit()"

