#!/bin/bash
#SBATCH --job-name=clinical
#SBATCH --time=06:00:00
#SBATCH --ntasks=1
#SBATCH --mem-per-cpu=6G
#SBATCH --cpus-per-task=1
#SBATCH --output=clinical_gather-%A_%a.out

source /path/to/miniconda/bin/activate

python output_clinical_outcomes_annual_boosting_1.py
python output_clinical_outcomes_annual_boosting_1_median.py
python output_clinical_outcomes_annual_boosting_1_quantiles.py

python output_clinical_outcomes_annual_boosting_1_younger.py
python output_clinical_outcomes_annual_boosting_1_younger_median.py
python output_clinical_outcomes_annual_boosting_1_younger_quantiles.py

